### PR TITLE
remove homepage migration

### PR DESCRIPTION
**Pull request by tomasmoose**
https://www.pivotaltracker.com/n/projects/2153753/stories/159305679

Removing the migration we did some month ago, keeping the old backbone pages as thats a different beast. 

The task is a chore, so feel free to accept when merged and accepted

### CODE REVIEW

**Comment by clementprdhomme** [comment]
Hey @tomasmoose!

I think that because Quill.js was removed, the wysiwyg of the "Open Content v1" type of page isn't working anymore. I'm not sure whether we should still support it or remove its option.

**Comment by tomasmoose** [comment]
@clementprdhomme @santostiago  you think we still need to support it?

**Comment by tomasmoose** [comment]
We are going to remove the `open_content_v1` type in another pr when tiago does a refactor. Lets keep this pr open until thats done.

**Comment by santostiago** [comment]
@tomasmoose can I close this?

**Pull request closed without merging**
