### PR TITLE
wysiwyg updates and improvements

### PR DESCRIPTION
**Pull request by tomasmoose**
1. Now you can add captions to photos. Also added some styling and improvements to the form in general
2. You can now remove individual items within a column.

https://www.pivotaltracker.com/story/show/158860270
https://www.pivotaltracker.com/story/show/159142993
https://www.pivotaltracker.com/story/show/158860330

### CODE REVIEW

**Comment by clementprdhomme** [comment]
@tomasmoose In the SASS file, I think you should use the variables we have in `settings-theme-XXX.scss`.

**Comment by clementprdhomme** [comment]
I think the last commit you pushed as an issue with at least one of the themes: the caption of the images are white for me so I don't see them.

I also got this warning when adding an image with a caption:
Warning: Use the `defaultValue` or `value` props instead of setting children on <textarea>.

Finally, when I add a text element and a widget in a column and then delete the widget, both the elements get deleted.

**Comment by tomasmoose** [comment]
in this case we dont care about that warning, we need to do it like this :)

**Comment by tomasmoose** [comment]
whats the issue @clementprdhomme  ?

**Comment by clementprdhomme** [comment]
Hey @tomasmoose,

So I've pulled the latest change in your branch and run `yarn`. All my tests have been done in the back-office.

Here are the two issues:
1. The caption is not shown when adding an image or when the wysiwyg is in read only mode. You can see below the colour of the text is white.

When adding an image, the caption doesn't appear. In the dev tools, we can see the text colour is set to white.

2. When I add two blocks in the same column, if I delete one of them, both disappear. I've tested this with other blocks than text too.

Two text blocks are added in the first column of a grid. When deleting the second one, both disappear.

**Pull request merged**
