### PR TITLE
Added tagged route cache

### PR DESCRIPTION
**Pull request by tiagojsag**
[WIP] - DO NOT MERGE

Motivation: routing in rails is not meant to be dynamic, so it's loaded on app start and never reloaded automatically during runtime. As we have dynamic routing, we need to explicitly call the routing reloader on certain events, specifically Page, Site and Route saves.

As the site grows, a full reload will require a full read on the Page-Site-Route triplet from DB, which will not scale at all. To avoid that, I introduced a tagging layer on top of Rails.cache, so that we can tag routes with their matching Site, Route and Page. Thus, we can limit changes to the routes associated with changed elements, and have decent, scalable performance.

### CODE REVIEW

**Comment by tiagojsag** [comment]
Currently still missing the actual route reload, but that should be easy enough. Also, this is meant to work correctly even when the cache is disabled (as all good cached apps should). Hasn't been properly tested, specially with passenger. We might have to move away to an external cache (Redis/Memcached), as I suspect ruby does not natively support shared memory cache.

**Comment by adammulligan** [comment]
You write pretty good Ruby for a PHPist 😛 . This seems good to me so far. I think moving to memcached or something is a good idea, but let's see if this works first.

For something as important and potentially complex as the routing, I think some tests would be good, possibly even just some higher level integration-style tests to see if routes are updating, etc. What do you think?

**Comment by tiagojsag** [comment]
what do you mean "You write pretty good Ruby for a PHPist"? my ruby code is the best! :P
About the tests, yeah, I agree with you, was just feeling lazy yesterday. I'll add them later on

**Comment by adammulligan** [comment]
😀 

thanks!

**Pull request merged**
