### PR TITLE
Feat/vega charts

### PR DESCRIPTION
**Pull request by sorodrigo**
This PR restyles the vega charts.

1. Donut Chart
screen shot 2017-03-31 at 14 33 29

2. Bar Chart
screen shot 2017-03-31 at 14 29 13

3. Scatter Plot Chart
screen shot 2017-03-31 at 17 00 29

4. Line Chart
screen shot 2017-03-31 at 19 26 23

### CODE REVIEW

**Comment by sorodrigo** [comment]
I have no appropriate data to test the line chart, but seems to be working.

**Comment by tiagojsag** [comment]
image

We need to improve the labels on these cases

**Comment by sorodrigo** [comment]
screen shot 2017-04-03 at 20 19 04

Tested with the following dummy data:
```[
        {"acq_date": "01-01-2017", "cartodb_id": 1},
        {"acq_date": "01-03-2017", "cartodb_id": 2},
        {"acq_date": "01-06-2017", "cartodb_id": 3},
        {"acq_date": "01-07-2017", "cartodb_id": 4},
        {"acq_date": "01-08-2017", "cartodb_id": 5},
        {"acq_date": "01-09-2017", "cartodb_id": 6},
        {"acq_date": "01-12-2017", "cartodb_id": 7}
        ]```

**Comment by sorodrigo** [comment]
screen shot 2017-04-03 at 20 31 02
Now the legends occupy the complete height of the widget, but even with these there's a max number of elements before it becomes unreadable.

**Pull request merged**
